latest upgrade script - move things to user space.

diff --git a/resources/update-nodejs-and-nodered b/resources/update-nodejs-and-nodered
--- a/resources/update-nodejs-and-nodered
+++ b/resources/update-nodejs-and-nodered
@@ -14,7 +14,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 if [ "$EUID" == "0" ]
-  then echo -en "\nRoot user detected. Typically install as a normal user. No need for sudo.\r\n"
+  then echo -en "\nRoot user detected. Typically install as a normal user. No need for sudo.\r\n\r\n"
   read -p "Are you really sure you want to install as root ? (y/N) ? " yn
   case $yn in
     [Yy]* )
@@ -24,23 +24,42 @@ if [ "$EUID" == "0" ]
     ;;
   esac
 fi
+wget -q --spider https://www.npmjs.com/package/node-red
+if  [ $? -eq 0 ]; then
 if [[ "$(uname)" != "Darwin" ]]; then
 if [[ $(cat /etc/*-release | grep VERSION=) != *"wheezy"* ]]; then
 echo -e '\033]2;'Node-RED update'\007'
 echo " "
 echo "This script will remove any pre-installed versions of node.js and Node-RED"
 echo "and replace them with node.js 6.x LTS (boron) and the latest Node-RED from Npm."
-echo "To do this it runs commands as root - please satisfy yourself that this will"
+echo " "
+echo "It also moves any Node-RED nodes that are globally installed into your user"
+echo "~/.node-red/node_modules directory, and adds them to your package.json, so that"
+echo "you can manage them with the palette manager."
+echo " "
+echo "It also tries to run 'npm rebuild' to refresh any extra nodes you have installed"
+echo "that may have a native binary component. While this normally works ok, you need"
+echo "to check that it succeeds for your combination of installed nodes."
+echo " "
+echo "To do all this it runs commands as root - please satisfy yourself that this will"
 echo "not damage your Pi, or otherwise compromise your configuration."
+echo "If in doubt please backup your SD card first."
 echo " "
-echo "Doing this may also be 'a bad thing' if you have installed lots of extra nodes."
-echo "Especially if they have any native binary component. Some nodes in your"
-echo "~/.node-red directory will probably need to be re-installed afterwards, some"
-echo "may need you to run npm update, and some may require you to run npm rebuild."
-echo " "
-read -p "Are you really sure you want to do this ? (y/N) ? " yn
+
+read -p "Are you really sure you want to do this ? [y/N] ? " yn
 case $yn in
     [Yy]* )
+        echo ""
+        EXTRANODES=""
+        EXTRAW="update"
+        if [ ! -d "/usr/lib/node_modules/node-red-node-serialport" ] && [ ! -d "$HOME/.node-red/node_modules/node-red-node-serialport" ]; then
+            read -r -t 15 -p "Would you like to install the Pi-specific nodes ? [y/N] ? " response
+            if [[ "$response" =~ ^([yY])+$ ]]; then
+                EXTRANODES="node-red-node-random node-red-contrib-ibm-watson-iot node-red-node-ping node-red-contrib-play-audio node-red-node-smooth node-red-node-serialport"
+                EXTRAW="install"
+            fi
+        fi
+
         # this script assumes that $HOME is the folder of the user that runs node-red
         # that $USER is the user name and the group name to use when running is the
         # primary group of that user
@@ -48,13 +67,16 @@ case $yn in
         NODERED_HOME=$HOME
         NODERED_USER=$USER
         NODERED_GROUP=`id -gn`
+        GLOBAL="true"
         TICK='\033[1;32m\u2714\033[0m'
         CROSS='\033[1;31m\u2718\033[0m'
         cd "$NODERED_HOME" || exit 1
         clear
-        echo "Running for user $USER at $HOME"
+        echo "Running Node-RED $EXTRAW for user $USER at $HOME"
         time1=$(date)
-        echo "\n\n***********************************" | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        echo "" | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        echo "***************************************" | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        echo "" | sudo tee -a /var/log/nodered-install.log >>/dev/null
         echo "Started : "$time1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
         echo "Running for user $USER at $HOME" | sudo tee -a /var/log/nodered-install.log >>/dev/null
         echo -ne '\r\nThis can take 20-30 minutes on a Pi 1 - please wait.\r\n\n'
@@ -64,8 +86,8 @@ case $yn in
         echo -ne '  Install node.js                     \r\n'
         echo -ne '  Clean npm cache                     \r\n'
         echo -ne '  Install Node-RED core               \r\n'
-        echo -ne '  Install extra nodes                 \r\n'
-        echo -ne '  Install serialport node             \r\n'
+        echo -ne '  Move global nodes to local          \r\n'
+        echo -ne '  Install extra Pi nodes              \r\n'
         echo -ne '  Npm rebuild existing nodes          \r\n'
         echo -ne '  Add menu shortcut                   \r\n'
         echo -ne '  Update systemd script               \r\n'
@@ -77,6 +99,11 @@ case $yn in
         if sudo service nodered stop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null ; then CHAR=$TICK; else CHAR=$CROSS; fi
         echo -ne "  Stop Node-RED                       $CHAR\r\n"
 
+        # save any global nodes
+        GLOBALNODES=$(find /usr/local/lib/node_modules/node-red-* -maxdepth 0 -type d -printf '%f\n' 2>/dev/null)
+        GLOBALNODES="$GLOBALNODES $(find /usr/lib/node_modules/node-red-* -maxdepth 0 -type d -printf '%f\n' 2>/dev/null)"
+        echo "Found global nodes: $GLOBALNODES :" | sudo tee -a /var/log/nodered-install.log >>/dev/null
+
         # remove any old node-red installs or files
         sudo apt-get remove -y nodered 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
         sudo rm -rf /usr/local/lib/node_modules/node-red* /usr/local/bin/node-red* 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
@@ -85,12 +112,14 @@ case $yn in
 
         # maybe remove node.js - or upgrade if nodesoure.list exists
         if [[ -e $NODERED_HOME/.nvm ]]; then
-            echo -ne '  Using NVM to manage node.js         +   please run   \033[0;36mnvm use lts/*\033[0m\r\n'
+            echo -ne '  Using NVM to manage node.js         +   please run   \033[0;36mnvm use lts/*\033[0m   before running ./node-red\r\n'
             export NVM_DIR=$NODERED_HOME/.nvm
             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-            nvm install lts/* >/dev/null 2>&1
+            nvm install --lts/* >/dev/null 2>&1
             nvm use lts/* >/dev/null 2>&1
             nvm alias default lts/* >/dev/null 2>&1
+            GLOBAL="false"
+            ln -f -s $NODERED_HOME/.nvm/versions/node/$(nvm current)/lib/node_modules/node-red/red.js  $NODERED_HOME/node-red
             echo -ne "  Update node.js LTS                  $CHAR"
         elif [[ $(which n) ]]; then
             echo -ne "  Using N to manage node.js           +\r\n"
@@ -99,7 +128,8 @@ case $yn in
         elif [ -e /etc/apt/sources.list.d/nodesource.list ]; then
             nv=`node -v | cut -d "." -f1`
             if [ "$nv" = "v0" ] || [ "$nv" = "v1" ] || [ "$nv" = "v3" ] || [ "$nv" = "v4" ] || [ "$nv" = "v5" ]; then
-                sudo rm -rf /etc/apt/sources.d/nodesource.list
+                sudo apt-get remove -y nodejs nodejs-legacy npm 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+                sudo rm -f /etc/apt/sources.d/nodesource.list
                 if curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
             else
                 CHAR="-"
@@ -113,7 +143,7 @@ case $yn in
             sudo apt-get remove -y nodejs nodejs-legacy npm 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             sudo dpkg -r nodejs 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             sudo dpkg -r node 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-            sudo rm -rf /usr/local/bin/npm* 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo rm -f /usr/local/bin/npm* 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             sudo apt-get autoremove -y 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             echo -ne "  Remove old version of node.js       \033[1;32m\u2714\033[0m\r\n"
             # grab the correct LTS bundle for the processor
@@ -122,7 +152,12 @@ case $yn in
                 f=$(curl -sL https://nodejs.org/download/release/latest-boron/ | grep "armv6l.tar.gz" | cut -d '"' -f 2)
                 curl -sL -o node.tgz https://nodejs.org/download/release/latest-boron/$f 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
                 # unpack it into the correct places
-                if sudo tar -zxf node.tgz --strip-components=1 -C /usr 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+                hd=$(head -c 9 node.tgz)
+                if [ "$hd" == "<!DOCTYPE" ]; then
+                    CHAR="$CROSS File $f not downloaded";
+                else
+                    if sudo tar -zxf node.tgz --strip-components=1 -C /usr 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+                fi
                 # remove the tgz file to save space
                 rm node.tgz 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
                 echo -ne "  Install node.js for Armv6           $CHAR"
@@ -146,48 +181,70 @@ case $yn in
         fi
 
         # clean up the npm cache and node-gyp
-        sudo npm cache clean --force 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        if [[ $GLOBAL == "true" ]]; then
+            sudo npm cache clean --force 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        else
+            npm cache clean --force 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+        fi
         if sudo rm -rf "$NODERED_HOME/.node-gyp" "$NODERED_HOME/.npm" /root/.node-gyp /root/.npm; then CHAR=$TICK; else CHAR=$CROSS; fi
         echo -ne "  Clean npm cache                     $CHAR\r\n"
 
         # and install Node-RED
-        if sudo npm i -g --unsafe-perm --no-progress node-red 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+        if [[ $GLOBAL == "true" ]]; then
+            if sudo npm i -g --unsafe-perm --no-progress node-red 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+        else
+            if npm i -g --unsafe-perm --no-progress node-red 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+        fi
         nrv=$(npm --no-progress -g ls node-red | grep node-red | cut -d '@' -f 2 | sudo tee -a /var/log/nodered-install.log) >>/dev/null 2>&1
         echo -ne "  Install Node-RED core               $CHAR   $nrv\r\n"
 
-        # install extra nodes - random, ping, smooth, iot, play-audio
-        if sudo npm i -g --unsafe-perm --no-progress node-red-node-random node-red-node-ping node-red-node-smooth node-red-contrib-ibm-watson-iot node-red-contrib-play-audio 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
-        # install Pi nodes (and remove GPIO if not on Pi)
-        if sudo grep -q BCM2 /proc/cpuinfo; then
-            sudo npm i -g --unsafe-perm --no-progress node-red-node-ledborg node-red-node-pi-sense-hat 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        else
-            sudo rm -rf /usr/lib/node_modules/node-red/nodes/core/hardware/36*
-        fi
-        echo -ne "  Install extra nodes                 $CHAR\r\n"
+        # install any nodes, that were installed globally, as local instead
+        mkdir -p "$NODERED_HOME/.node-red/node_modules"
+        sudo chown -R $NODERED_USER:$NODERED_GROUP $NODERED_HOME/.node-red/ 2>&1 >>/dev/null
+        pushd "$NODERED_HOME/.node-red" 2>&1 >>/dev/null
+            if [ ! -f "package.json" ]; then
+                echo '{' > package.json
+                echo '  "name": "node-red-project",' >> package.json
+                echo '  "description": "A Node-RED Project",' >> package.json
+                echo '  "version": "0.0.1",' >> package.json
+                echo '  "dependencies": {' >> package.json
+                echo '  }' >> package.json
+                echo '}' >> package.json
+            fi
+            CHAR="-"
+            if [[ $GLOBALNODES != " " ]]; then
+                if npm i --unsafe-perm --save --no-progress $GLOBALNODES 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+            fi
+            echo -ne "  Move global nodes to local          $CHAR\r\n"
 
-        # remove and re-install serialport (won't need to on/after 0.16)
-        sudo rm -rf /usr/lib/node_modules/node-red/node_modules/node-red-node-serialport
-        if sudo npm i -g --unsafe-perm --no-progress node-red-node-serialport 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
-        echo -ne "  Install serialport node             $CHAR\r\n"
+            CHAR="-"
+            if [[ ! -z $EXTRANODES ]]; then
+                echo "Installing extra nodes: $EXTRANODES :" | sudo tee -a /var/log/nodered-install.log >>/dev/null
+                if npm i --unsafe-perm --save --no-progress $EXTRANODES 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
+            fi
+            echo -ne "  Install extra Pi nodes              $CHAR\r\n"
 
-        # try to rebuild any already installed nodes
-        if [ -d "$NODERED_HOME/.node-red" ]; then
-            pushd "$NODERED_HOME/.node-red" 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-            if [ -e "node_modules/node-red-node-serialport" ]; then rm -rf node_modules/node-red-node-serialport; fi
+            # try to rebuild any already installed nodes
             if npm rebuild  2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
-            popd 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        fi
-        echo -ne "  Npm rebuild existing nodes          $CHAR\r\n"
+            echo -ne "  Npm rebuild existing nodes          $CHAR\r\n"
+        popd 2>&1 >>/dev/null
 
         # add the shortcut and start/stop/log scripts to the menu
-        sudo curl -sL -o /usr/share/icons/gnome/scalable/apps/node-red-icon.svg https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-icon.svg 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        sudo curl -sL -o /usr/share/applications/Node-RED.desktop https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/Node-RED.desktop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        sudo curl -sL -o /usr/bin/node-red-start https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-start2 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        sudo curl -sL -o /usr/bin/node-red-stop https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-stop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        sudo curl -sL -o /usr/bin/node-red-log https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-log 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-        sudo chmod +x /usr/bin/node-red-st*
-        sudo chmod +x /usr/bin/node-red-log
-        echo -ne "  Add menu shortcut                   \033[1;32m\u2714\033[0m\r\n"
+        sudo mkdir -p /usr/bin
+        wget -q --spider https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-icon.svg
+        if  [ $? -eq 0 ]; then
+            sudo curl -sL -o /usr/share/icons/gnome/scalable/apps/node-red-icon.svg https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-icon.svg 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo curl -sL -o /usr/share/applications/Node-RED.desktop https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/Node-RED.desktop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo curl -sL -o /usr/bin/node-red-start https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-start2 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo curl -sL -o /usr/bin/node-red-stop https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-stop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo curl -sL -o /usr/bin/node-red-log https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-log 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
+            sudo chmod +x /usr/bin/node-red-start
+            sudo chmod +x /usr/bin/node-red-stop
+            sudo chmod +x /usr/bin/node-red-log
+            echo -ne "  Add menu shortcut                   $TICK\r\n"
+        else
+            echo -ne "  Add menu shortcut                   $CROSS\r\n"
+        fi
 
         # add systemd script and configure it for $USER
         if sudo curl -sL -o /lib/systemd/system/nodered.service https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/nodered.service 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
@@ -202,7 +259,6 @@ case $yn in
             sudo curl -sL -o /usr/lib/node_modules/node-red-contrib-ibm-watson-iot/examples/Pi\ cpu\ temperature.json https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/Pi%20cpu%20temperature.json 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             sudo setcap cap_net_raw+eip $(eval readlink -f `which node`) 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             sudo setcap cap_net_raw=ep /bin/ping 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-            sudo setcap cap_net_raw=ep /bin/ping6 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
         fi
 
         # Finally update the update script
@@ -212,8 +268,12 @@ case $yn in
 
         echo -ne "\r\n\r\n\r\n"
         echo -ne "All done.\r\n"
-        echo -ne "  You can now start Node-RED with the command  \033[0;36mnode-red-start\033[0m\r\n"
-        echo -ne "  or using the icon under   Menu / Programming / Node-RED\r\n"
+        if [[ $GLOBAL == "true" ]]; then
+            echo -ne "  You can now start Node-RED with the command  \033[0;36mnode-red-start\033[0m\r\n"
+            echo -ne "  or using the icon under   Menu / Programming / Node-RED\r\n"
+        else
+            echo -ne "  You can now start Node-RED with the command  \033[0;36m./node-red\033[0m\r\n"
+        fi
         echo -ne "  Then point your browser to \033[0;36mlocalhost:1880\033[0m or \033[0;36mhttp://{your_pi_ip-address}:1880\033[0m\r\n"
         echo -ne "\r\nStarted  $time1  -  Finished  $(date)\r\n\r\n"
         echo "Finished : "$time1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
@@ -234,6 +294,14 @@ else
 echo " "
 echo "Sorry - I'm not supposed to be run on a Mac."
 echo "Please see the documentation at http://nodered.org/docs/getting-started/upgrading."
+echo " "
+exit 1
+fi
+else
+echo " "
+echo "Sorry - cannot connect to internet - not going to touch anything."
+echo "https://www.npmjs.com/package/node-red   is not reachable."
+echo "Please ensure you have a working internet connection."
 echo " "
 exit 1
 fi
