Update pi updater
to detect wheezy earlier
tidy up license and copyright

diff --git a/resources/update-nodejs-and-nodered b/resources/update-nodejs-and-nodered
--- a/resources/update-nodejs-and-nodered
+++ b/resources/update-nodejs-and-nodered
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
-# Copyright 2016,2017 IBM Corp.
+# Copyright 2016,2018 JS Foundation and other contributors, https://js.foundation/
+# Copyright 2015,2016 IBM Corp.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -37,10 +38,10 @@ if [ "$EUID" == "0" ]
     ;;
   esac
 fi
+if [[ $(cat /etc/*-release | grep VERSION=) != *"wheezy"* ]]; then
+if [[ "$(uname)" != "Darwin" ]]; then
 wget -q --spider https://www.npmjs.com/package/node-red
 if  [ $? -eq 0 ]; then
-if [[ "$(uname)" != "Darwin" ]]; then
-if [[ $(cat /etc/*-release | grep VERSION=) != *"wheezy"* ]]; then
 echo -e '\033]2;'Node-RED update'\007'
 echo " "
 echo "This script will remove versions of Node.js prior to version 6.x of Node.js and Node-RED"
@@ -299,8 +300,10 @@ case $yn in
 esac
 else
 echo " "
-echo "Sorry - I'm not able to upgrade old Wheezy installations. Please think about updating."
-echo "Please see the documentation at http://nodered.org/docs/getting-started/upgrading."
+echo "Sorry - cannot connect to internet - not going to touch anything."
+echo "https://www.npmjs.com/package/node-red   is not reachable."
+echo "Please ensure you have a working internet connection."
+echo "Return code from wget is "$?
 echo " "
 exit 1
 fi
@@ -313,9 +316,8 @@ exit 1
 fi
 else
 echo " "
-echo "Sorry - cannot connect to internet - not going to touch anything."
-echo "https://www.npmjs.com/package/node-red   is not reachable."
-echo "Please ensure you have a working internet connection."
+echo "Sorry - I'm not able to upgrade old Wheezy installations. Please think about updating."
+echo "Please see the documentation at http://nodered.org/docs/getting-started/upgrading."
 echo " "
 exit 1
 fi
