don't try to update wheezy installs

diff --git a/resources/update-nodejs-and-nodered b/resources/update-nodejs-and-nodered
--- a/resources/update-nodejs-and-nodered
+++ b/resources/update-nodejs-and-nodered
@@ -13,6 +13,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
+if [[ $(cat /etc/*-release | grep VERSION=) != *"wheezy"* ]]; then
 echo -e '\033]2;'Node-RED update'\007'
 echo " "
 echo "This script will remove any pre-installed versions of node.js and Node-RED"
@@ -39,13 +40,12 @@ case $yn in
         NODERED_GROUP=`id -gn`
         TICK='\033[1;32m\u2714\033[0m'
         CROSS='\033[1;31m\u2718\033[0m'
-        time1=$(date)
-        sudo rm /var/log/nodered-install.log
+        cd "$NODERED_HOME" || exit 1
         clear
+        time1=$(date)
+        sudo rm -f /var/log/nodered-install.log
         echo "Started : "$time1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
-
-        cd "$NODERED_HOME"
-        echo -ne "\r\nThis can take 20-30 minutes on a Pi 1 - please wait.\r\n\n"
+        echo -ne '\r\nThis can take 20-30 minutes on a Pi 1 - please wait.\r\n\n'
         echo -ne '  Stop Node-RED                       \r\n'
         echo -ne '  Remove old version of Node-RED      \r\n'
         echo -ne '  Remove old version of node.js       \r\n'
@@ -61,7 +61,7 @@ case $yn in
         echo -ne '\r\nAny errors will be logged to   /var/log/nodered-install.log\r\n'
         echo -ne '\033[14A'
 
-        if node-red-stop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null ; then CHAR=$TICK; else CHAR=$CROSS; fi
+        if sudo service nodered stop 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null ; then CHAR=$TICK; else CHAR=$CROSS; fi
         echo -ne "  Stop Node-RED                       $CHAR\r\n"
 
         sudo apt-get remove -y nodered 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
@@ -82,7 +82,7 @@ case $yn in
             sudo apt-get autoremove -y 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
             echo -ne '  Remove old version of node.js       \033[1;32m\u2714\033[0m\r\n'
             # grab the correct LTS bundle for the processor
-            if $(cat /proc/cpuinfo | grep model | grep -q ARMv6) ; then
+            if cat /proc/cpuinfo | grep model | grep -q ARMv6 ; then
                 echo -ne "  Install node.js for Armv6           \r"
                 f=$(wget https://nodejs.org/download/release/latest-boron/ -qO- | grep "armv6l.tar.gz" | cut -d '"' -f 2)
                 wget https://nodejs.org/download/release/latest-boron/$f -O node.tgz 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
@@ -100,14 +100,22 @@ case $yn in
             fi
         fi
         hash -r
-        #echo "Installed"
-        echo -ne "   Node $(node -v)   Npm $(npm -v)\r\n"
+        rc=""
+        if nov=$(node -v 2>/dev/null); then :; else rc="ERR"; fi
+        if npv=$(npm -v 2>/dev/null); then :; else rc="ERR"; fi
+        if [[ $rc == "" ]]; then
+            echo -ne "   Node $nov   Npm $npv\r\n"
+        else
+            echo -ne "\b$CROSS   Failed to install node.js - Exit\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n"
+            exit 2
+        fi
         # and install Node-RED
         sudo npm cache clean 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
         if sudo rm -rf "$NODERED_HOME/.node-gyp" "$NODERED_HOME/.npm" /root/.node-gyp /root/.npm; then CHAR=$TICK; else CHAR=$CROSS; fi
         echo -ne "  Clean npm cache                     $CHAR\r\n"
         if sudo npm i -g --unsafe-perm --no-progress node-red 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
-        echo -ne "  Install Node-RED core               $CHAR\r\n"
+        nrv=$(npm --no-progress -g ls node-red | grep node-red | cut -d '@' -f 2 | sudo tee -a /var/log/nodered-install.log) >>/dev/null 2>&1
+        echo -ne "  Install Node-RED core               $CHAR   $nrv\r\n"
         if sudo npm i -g --unsafe-perm --no-progress node-red-node-random node-red-node-ping node-red-node-smooth node-red-contrib-ibm-watson-iot node-red-contrib-play-audio 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null; then CHAR=$TICK; else CHAR=$CROSS; fi
         if sudo grep -q BCM270 /proc/cpuinfo; then
             sudo npm i -g --unsafe-perm --no-progress node-red-node-ledborg node-red-node-pi-sense-hat 2>&1 | sudo tee -a /var/log/nodered-install.log >>/dev/null
@@ -162,3 +170,10 @@ case $yn in
         exit 1
     ;;
 esac
+else
+echo " "
+echo "Sorry - I'm not able to upgrade old Wheezy installations. Please think about updating."
+echo "See the documentation at http://nodered.org/docs/getting-started/upgrading."
+echo " "
+exit 1
+fi
